server:
  port: 8080
#  context-path: /sell
spring:
  application:
    name: sell
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.107/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
#    hibernate.enable_lazy_load_no_trans=true 除去延迟加载
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: D:/project/weixin_sell/Wechat-Ordering
#    level:
#      com.wga.sell.service.LogTest: debug